steps:
- name: 'curlimages/curl'
  entrypoint: 'sh'
  args:
    - -c
    - |
      chmod +x scripts/trigger_github_workflow.sh
      scripts/trigger_github_workflow.sh

options:
  logging: CLOUD_LOGGING_ONLY